[project]
name = "teacheragent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LuoHui", email = "lilisama20203@163.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "neo4j>=6.3.0",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.1",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
teacheragent = "teacheragent:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["src/teacheragent/tests"]
